name: CI
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
    MAVEN_OPTS: >-
        -Dhttp.keepAlive=false
        -Dmaven.wagon.http.pool=false
        -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
        
jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Use Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
      - name: SonarCloud Scan
        uses: jason-fox/sonarcloud-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_CLOUD_LOGIN: ${{ secrets.SONAR_CLOUD_LOGIN }}

  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Run DITA-OT Unit Test
        uses: jason-fox/dita-unit-test-action@master
        with:
          dita-ot-version: '4.2'
          plugin: 'fox.jason.prismjs'
          prerequisites: fox.jason.extend.css
          setup-script: 'test/setup.sh'
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: test-results.html
